### ISSUE TITLE
Errors while cfbackup runs

### ISSUE THREAD

**Issue by nazeeronline** [jmstacey/cfbackup#21]
Hi,

Thanks for the great backup tool : cfbackup

I am getting a small error when I am running the backups
# 

cfbackup --action push -v -r --local_path /backup/ --container test
Establishing connection... done.
There are 38 files to process.
(1/38) Skipping cpbackup
(2/38) Skipping cpbackup/monthly
(3/38) Pushing file cpbackup/monthly/stayatad.tar.gz.../usr/lib/ruby/gems/1.8/gems/rackspace-cloudfiles-1.4.0.0/lib/cloudfiles/storage_object.rb:50:in `populate': Object cpbackup/monthly does not exist (NoSuchObjectException)
        from /usr/lib/ruby/gems/1.8/gems/rackspace-cloudfiles-1.4.0.0/lib/cloudfiles/storage_object.rb:175:in`write'
        from /usr/lib/ruby/gems/1.8/gems/rackspace-cloudfiles-1.4.0.0/lib/cloudfiles/storage_object.rb:249:in `make_path'
        from /usr/lib/ruby/gems/1.8/gems/rackspace-cloudfiles-1.4.0.0/lib/cloudfiles/storage_object.rb:174:in`write'
        from /usr/lib/ruby/gems/1.8/gems/rackspace-cloudfiles-1.4.0.0/lib/cloudfiles/storage_object.rb:196:in `load_from_filename'
        from /usr/lib/ruby/gems/1.8/gems/jmstacey-cfbackup-0.7.1/lib/cfbackup.rb:149:in`push_files'
        from /usr/lib/ruby/gems/1.8/gems/jmstacey-cfbackup-0.7.1/lib/cfbackup.rb:132:in `each'
        from /usr/lib/ruby/gems/1.8/gems/jmstacey-cfbackup-0.7.1/lib/cfbackup.rb:132:in`push_files'
        from /usr/lib/ruby/gems/1.8/gems/jmstacey-cfbackup-0.7.1/lib/cfbackup.rb:63:in `run'
        from /usr/lib/ruby/gems/1.8/gems/jmstacey-cfbackup-0.7.1/bin/cfbackup:6
        from /usr/bin/cfbackup:23:in`load'
        from /usr/bin/cfbackup:23
# 

Can you please let me know where is it going wrong..

Thanks

Nazeer

**Comment by jmstacey** [comment]
Strange. I'll see if I can reproduce this when I'm back from travels next week and see what's going on here.

**Comment by jmstacey** [comment]
I haven't had a chance to reproduce this locally, or run the test suite but from the errors you posted I would say either (1) the container doesn't exist yet, or (2) perhaps there was an API change in the upstream Rackspace library that's breaking the way file structure is handled.

If you checkout the master branch and run the test suite (i.e. don't run the gem), do the tests check out?
